name: 03-workflow-runners

on:
  workflow_dispatch

jobs:
  echo-runner-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "OS: $RUNNER_OS"

  echo-runner-Windows:
    runs-on: windows-latest
    steps:
      - name: echo
        shell: bash
        run: |
          echo "OS: $RUNNER_OS"

  echo-runner-MacOS:
    runs-on: macos-latest
    steps:
      - name: echo
        run: |
          echo "OS: $RUNNER_OS"